<?php 

if(function_exists('acf_add_local_field_group') ) :

    acf_add_local_field_group(
        array(
        'key' => 'group_nav_item_options',
        'title' => 'Nav Item Options',
        'fields' => array(
        array(
            'key' => 'field_6116eb93dfc3d',
            'label' => 'Nav Item Options',
            'name' => 'nav_item_options',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_save_meta' => 0,
            'layout' => 'block',
            'acfe_seamless_style' => 1,
            'acfe_group_modal' => 0,
            'sub_fields' => array(
                array(
                    'key' => 'field_6116eb93ea681',
                    'label' => 'Type',
                    'name' => 'type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_permissions' => '',
                    'choices' => array(
                        'nav' => 'Basic navigation list',
                        'navbar' => 'A site navigation bar',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6116eb93ea69a',
                    'label' => 'Background Color',
                    'name' => 'background_color',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'transparent' => 'Transparent',
                        'primary' => 'Theme Primary Color',
                        'secondary' => 'Theme Secondary Color',
                        'tertiary' => 'Theme Tertiary Color',
                        'custom' => 'Custom Color',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'allow_custom' => 0,
                    'search_placeholder' => '',
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6116eb93ea6a4',
                    'label' => 'Custom Background Color',
                    'name' => 'custom_background_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        array(
                            array(
                                'field' => 'field_6116eb93ea69a',
                                'operator' => '==',
                                'value' => 'custom',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_permissions' => '',
                    'default_value' => '',
                ),
                array(
                    'key' => 'field_6116eb93ea6ad',
                    'label' => 'Child Menu Type',
                    'name' => 'child_type',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'none' => 'Flat style (no submenus)',
                        'collapse' => 'Accordion Style',
                        'dropdown' => 'Dropdown Style',
                        'tab' => 'Tab Style',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
                array(
                    'key' => 'field_6116ec8d46d4a',
                    'label' => 'Color',
                    'name' => 'color',
                    'type' => 'button_group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                    ),
                    'allow_null' => 1,
                    'default_value' => '',
                    'layout' => 'horizontal',
                    'return_format' => 'value',
                ),
            ),
        ),
        ),
        'location' => array(
        array(
            array(
                'param' => 'nav_menu_item',
                'operator' => '==',
                'value' => 'all',
            ),
        ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'acfe_display_title' => '',
        'acfe_autosync' => array(
        0 => 'php',
        ),
        'acfe_form' => 0,
        'acfe_meta' => '',
        'acfe_note' => '',
        'acfe_categories' => array(
        'plugin' => 'Plugin',
        ),
        'modified' => 1628894649,
        )
    );

endif;
