<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_61772c8846d4b',
	'title' => 'Reusable Fields',
	'fields' => array(
		array(
			'key' => 'field_61772ca5bb3c1',
			'label' => 'Background Color',
			'name' => 'bg_color',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 0,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_61772cbfbb3c2',
					'label' => 'Background Color',
					'name' => 'bs_bg_color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_save_meta' => 0,
					'choices' => array(
						': Default' => ': Default',
						'bg-primary' => 'Primary',
						'bg-secondary' => 'Secondary',
						'bg-success' => 'Success',
						'bg-info' => 'Info',
						'bg-warning' => 'Warning',
						'bg-danger' => 'Danger',
						'bg-light' => 'Light',
						'bg-dark' => 'Dark',
						'bg-blue' => 'Blue',
						'bg-indigo' => 'Indigo',
						'bg-purple' => 'Purple',
						'bg-pink' => 'Pink',
						'bg-red' => 'Red',
						'bg-orange' => 'Orange',
						'bg-yellow' => 'Yellow',
						'bg-green' => 'Green',
						'bg-teal' => 'Teal',
						'bg-cyan' => 'Cyan',
						'bg-white' => 'White',
						'bg-black' => 'Black',
						'bg-gray' => 'Gray',
						'custom' => 'Custom',
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'allow_custom' => 0,
					'placeholder' => '',
					'search_placeholder' => '',
					'show_column' => 0,
					'show_column_sortable' => 0,
					'show_column_weight' => 1000,
					'allow_quickedit' => 0,
					'allow_bulkedit' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
				array(
					'key' => 'field_61772cf0bb3c3',
					'label' => 'Custom Background Color',
					'name' => 'custom_bg_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_61772cbfbb3c2',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_save_meta' => 0,
					'default_value' => '',
					'enable_opacity' => 1,
					'return_format' => 'string',
					'show_column' => 0,
					'show_column_sortable' => 0,
					'show_column_weight' => 1000,
					'allow_quickedit' => 0,
					'allow_bulkedit' => 0,
					'acfe_settings' => '',
					'acfe_validate' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_permissions' => '',
	'acfe_form' => 1,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'plugin' => 'Plugin',
	),
	'modified' => 1635202371,
));

endif;