<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_cpt_testimonial_options',
	'title' => 'Testimonial Fields',
	'fields' => array(
		array(
			'key' => 'field_6165ff9295a77',
			'label' => 'Submitted By',
			'name' => 'author',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 1,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 1,
			'allow_bulkedit' => 0,
		),
		array(
			'key' => 'field_6165ffb495a78',
			'label' => 'Rating',
			'name' => 'rating',
			'type' => 'star_rating_field',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 1,
			'max_stars' => 5,
			'return_type' => 0,
			'allow_half' => 1,
		),
		array(
			'key' => 'field_6166024595a79',
			'label' => 'Date Posted',
			'name' => 'date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 1,
			'display_format' => 'm/d/Y',
			'return_format' => 'Ymd',
			'first_day' => 0,
			'show_column' => 1,
			'show_column_sortable' => 1,
			'show_column_weight' => 1000,
			'allow_quickedit' => 1,
			'allow_bulkedit' => 1,
		),
		array(
			'key' => 'field_6166027795a7a',
			'label' => 'Author Image',
			'name' => 'author_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'library' => 'all',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'rwp_testimonial',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => 'Testimonial Fields',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'post-type-fields' => 'Post Type Fields',
		'rwp-plugin' => 'RWP Plugin',
	),
	'modified' => 1635185317,
));

endif;