<?php
/** ============================================================================
 * Testimonial Custom Fields
 *
 * @package   RWP\/group_testimonial_options.php
 * @since     <<projectversion>>
 * @author    RIESTER <wordpress@riester.com>
 * @copyright 2020 - 2021 RIESTER Advertising Agency
 * @license   GPL-2.0+
 * ========================================================================== */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(array(
		'key'                   => 'group_cpt_team_member_options',
		'title'                 => 'Team Member',
		'fields'                => array(
			array(
				'key'                  => 'field_6169c1099139d',
				'label'                => 'Prefix',
				'name'                 => 'prefix',
				'type'                 => 'text',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => ' col-md-3',
					'id'    => '',
				),
				'acfe_save_meta'       => 0,
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
				'show_column'          => 0,
				'show_column_sortable' => 0,
				'show_column_weight'   => 1000,
				'allow_quickedit'      => 1,
				'allow_bulkedit'       => 0,
			),
			array(
				'key'                  => 'field_6169c1219139e',
				'label'                => 'Suffix',
				'name'                 => 'suffix',
				'type'                 => 'text',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => 'col-md-3',
					'id'    => '',
				),
				'acfe_save_meta'       => 0,
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
				'show_column'          => 0,
				'show_column_sortable' => 0,
				'show_column_weight'   => 1000,
				'allow_quickedit'      => 1,
				'allow_bulkedit'       => 0,
			),
			array(
				'key'                  => 'field_6169c12f9139f',
				'label'                => 'Job Title',
				'name'                 => 'job_title',
				'type'                 => 'text',
				'instructions'         => '',
				'required'             => 0,
				'conditional_logic'    => 0,
				'wrapper'              => array(
					'width' => '',
					'class' => 'col-md-6',
					'id'    => '',
				),
				'acfe_save_meta'       => 0,
				'default_value'        => '',
				'placeholder'          => '',
				'prepend'              => '',
				'append'               => '',
				'maxlength'            => '',
				'show_column'          => 0,
				'show_column_sortable' => 0,
				'show_column_weight'   => 1000,
				'allow_quickedit'      => 1,
				'allow_bulkedit'       => 0,
			),
			array(
				'key'                 => 'field_6169c14b913a0',
				'label'               => 'Contact Info',
				'name'                => 'contact_info',
				'type'                => 'group',
				'instructions'        => '',
				'required'            => 0,
				'conditional_logic'   => 0,
				'wrapper'             => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'layout'              => 'block',
				'acfe_seamless_style' => 1,
				'acfe_group_modal'    => 0,
				'sub_fields'          => array(
					array(
						'key'               => 'field_6169c159913a1',
						'label'             => 'Phone',
						'name'              => 'phone',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => 'col-md-6',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
						'maxlength'         => '',
					),
					array(
						'key'               => 'field_6169c168913a2',
						'label'             => 'Email',
						'name'              => 'email',
						'type'              => 'email',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => 'col-md-6',
							'id'    => '',
						),
						'default_value'     => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'                              => 'field_6169c174913a3',
						'label'                            => 'Social',
						'name'                             => 'social',
						'type'                             => 'flexible_content',
						'instructions'                     => '',
						'required'                         => 0,
						'conditional_logic'                => 0,
						'wrapper'                          => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_flexible_advanced'           => 0,
						'layouts'                          => array(
							'layout_6169c247be19e' => array(
								'key'                     => 'layout_6169c247be19e',
								'name'                    => 'facebook',
								'label'                   => 'Facebook',
								'display'                 => 'block',
								'sub_fields'              => array(
									array(
										'key'           => 'field_6169c255913a6',
										'label'         => 'Url',
										'name'          => 'url',
										'type'          => 'link',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'return_format' => '',
									),
								),
								'min'                     => '',
								'max'                     => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings'  => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category'  => false,
							),
							'layout_6169c26f913a7' => array(
								'key'                     => 'layout_6169c26f913a7',
								'name'                    => 'twitter',
								'label'                   => 'Twitter',
								'display'                 => 'block',
								'sub_fields'              => array(
									array(
										'key'           => 'field_6169c26f913a8',
										'label'         => 'Url',
										'name'          => 'url',
										'type'          => 'link',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'return_format' => '',
									),
								),
								'min'                     => '',
								'max'                     => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings'  => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category'  => false,
							),
							'layout_6169c27f913a9' => array(
								'key'                     => 'layout_6169c27f913a9',
								'name'                    => 'linkedin',
								'label'                   => 'LinkedIn',
								'display'                 => 'block',
								'sub_fields'              => array(
									array(
										'key'           => 'field_6169c27f913aa',
										'label'         => 'Url',
										'name'          => 'url',
										'type'          => 'link',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'return_format' => 'array',
									),
								),
								'min'                     => '',
								'max'                     => '',
								'acfe_flexible_render_template' => false,
								'acfe_flexible_render_style' => false,
								'acfe_flexible_render_script' => false,
								'acfe_flexible_thumbnail' => false,
								'acfe_flexible_settings'  => false,
								'acfe_flexible_settings_size' => 'medium',
								'acfe_flexible_modal_edit_size' => false,
								'acfe_flexible_category'  => false,
							),
						),
						'button_label'                     => 'Add Social Profile',
						'min'                              => '',
						'max'                              => '',
						'acfe_flexible_stylised_button'    => false,
						'acfe_flexible_hide_empty_message' => false,
						'acfe_flexible_empty_message'      => '',
						'acfe_flexible_layouts_templates'  => false,
						'acfe_flexible_layouts_previews'   => false,
						'acfe_flexible_layouts_placeholder' => false,
						'acfe_flexible_layouts_thumbnails' => false,
						'acfe_flexible_layouts_settings'   => false,
						'acfe_flexible_async'              => array(),
						'acfe_flexible_add_actions'        => array(),
						'acfe_flexible_remove_button'      => array(),
						'acfe_flexible_layouts_state'      => false,
						'acfe_flexible_modal_edit'         => array(
							'acfe_flexible_modal_edit_enabled' => false,
							'acfe_flexible_modal_edit_size'    => 'large',
						),
						'acfe_flexible_modal'              => array(
							'acfe_flexible_modal_enabled' => false,
							'acfe_flexible_modal_title'   => false,
							'acfe_flexible_modal_size'    => 'full',
							'acfe_flexible_modal_col'     => '4',
							'acfe_flexible_modal_categories' => false,
						),
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'rwp_team_member',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'acfe_display_title'    => '',
		'acfe_autosync'         => '',
		'acfe_form'             => 0,
		'acfe_meta'             => '',
		'acfe_note'             => '',
		'acfe_categories'       => array(
			'post-type-fields' => 'Post Type Fields',
			'rwp-plugin'       => 'RWP Plugin',
		),
	));

endif;
