<?php 

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group( array(
		'key'                   => 'group_nav_options',
		'title'                 => 'Nav Options',
		'fields'                => array(
			array(
				'key'                     => 'field_5fe15b0a697ca',
				'label'                   => 'Nav Options',
				'name'                    => 'nav_options',
				'type'                    => 'group',
				'instructions'            => '',
				'required'                => 0,
				'conditional_logic'       => 0,
				'wrapper'                 => array(
					'width' => '',
					'class' => 'label-none',
					'id'    => '',
				),
				'acfe_save_meta'          => 0,
				'layout'                  => 'block',
				'acfe_group_modal'        => 1,
				'acfe_group_modal_close'  => 0,
				'acfe_group_modal_button' => '',
				'acfe_group_modal_size'   => 'large',
				'sub_fields'              => array(
					array(
						'key'                  => 'field_5f97580f6830d',
						'label'                => 'Type',
						'name'                 => 'type',
						'type'                 => 'select',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => 'col-md-auto flex-fill',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'choices'              => array(
							'nav'    => 'Basic navigation list',
							'navbar' => 'A site navigation bar',
							'tabs'   => 'A tab menu',
							'pills'  => 'A pill menu',
						),
						'default_value'        => false,
						'allow_null'           => 0,
						'multiple'             => 0,
						'ui'                   => 0,
						'return_format'        => 'value',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
						'ajax'                 => 0,
						'placeholder'          => '',
					),
					array(
						'key'                  => 'field_5f97588b6830e',
						'label'                => 'Direction',
						'name'                 => 'direction',
						'type'                 => 'button_group',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => 'col-md-auto',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'choices'              => array(
							'vertical'   => 'Vertical',
							'horizontal' => 'Horizontal',
						),
						'allow_null'           => 0,
						'default_value'        => '',
						'layout'               => 'horizontal',
						'return_format'        => 'value',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'                  => 'field_5f9758b86830f',
						'label'                => 'Theme',
						'name'                 => 'theme',
						'type'                 => 'select',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => 'col-md-auto',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'choices'              => array(
							'dark'  => 'Dark Theme (light links on a dark background)',
							'light' => 'Light Theme (dark links on a light background)',
						),
						'default_value'        => false,
						'allow_null'           => 1,
						'multiple'             => 0,
						'ui'                   => 0,
						'return_format'        => 'value',
						'placeholder'          => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
						'ajax'                 => 0,
					),
					array(
						'key'                 => 'field_61772f56bd0bf',
						'label'               => 'Background Color',
						'name'                => 'bg_color',
						'type'                => 'clone',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => array(
							'width' => '',
							'class' => 'col-md-auto flex-fill',
							'id'    => '',
						),
						'acfe_save_meta'      => 0,
						'clone'               => array(
							0 => 'field_61772ca5bb3c1',
						),
						'display'             => 'group',
						'layout'              => 'block',
						'prefix_label'        => 0,
						'prefix_name'         => 0,
						'acfe_seamless_style' => 1,
						'acfe_clone_modal'    => 0,
					),
					array(
						'key'               => 'field_619447a3823d7',
						'label'             => 'Divider',
						'name'              => '',
						'type'              => 'admin_divider',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => 'text-white',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'spacer'            => false,
					),
					array(
						'key'               => 'field_628e7135e39f4',
						'label'             => 'Add Container',
						'name'              => 'add_container',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 1,
						'ui'                => 1,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'                  => 'field_6102fc495eeae',
						'label'                => 'Container ID',
						'name'                 => 'container_id',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => array(
							array(
								array(
									'field'    => 'field_628e7135e39f4',
									'operator' => '==',
									'value'    => '1',
								),
							),
						),
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'                  => 'field_5f9b133481faa',
						'label'                => 'Container Classes',
						'name'                 => 'container_class',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => array(
							array(
								array(
									'field'    => 'field_628e7135e39f4',
									'operator' => '==',
									'value'    => '1',
								),
							),
						),
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'                  => 'field_6102fc655eeb0',
						'label'                => 'Container Label',
						'name'                 => 'container_aria_label',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => array(
							array(
								array(
									'field'    => 'field_628e7135e39f4',
									'operator' => '==',
									'value'    => '1',
								),
							),
						),
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'               => 'field_6194479a823d6',
						'label'             => 'Divider',
						'name'              => '',
						'type'              => 'admin_divider',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'spacer'            => 1,
					),
					array(
						'key'                  => 'field_6102fc545eeaf',
						'label'                => 'Menu ID',
						'name'                 => 'menu_id',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => 'col-md-4',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'                  => 'field_5f9b133d81fab',
						'label'                => 'Menu Classes',
						'name'                 => 'menu_class',
						'type'                 => 'text',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => 'col-md-8',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'default_value'        => '',
						'placeholder'          => '',
						'prepend'              => '',
						'append'               => '',
						'maxlength'            => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
					),
					array(
						'key'               => 'field_61944791823d5',
						'label'             => 'Divider',
						'name'              => '',
						'type'              => 'admin_divider',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'spacer'            => 1,
					),
					array(
						'key'                 => 'field_5f9759a468312',
						'label'               => 'Navbar Options',
						'name'                => 'navbar',
						'type'                => 'group',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => array(
							array(
								array(
									'field'    => 'field_5f97580f6830d',
									'operator' => '==',
									'value'    => 'navbar',
								),
							),
						),
						'wrapper'             => array(
							'width' => '',
							'class' => 'label-lg border w-100',
							'id'    => '',
						),
						'acfe_save_meta'      => 0,
						'layout'              => 'block',
						'acfe_seamless_style' => 1,
						'acfe_group_modal'    => 0,
						'sub_fields'          => array(
							array(
								'key'                  => 'field_5f975a2168314',
								'label'                => 'Mobile Breakpoint',
								'name'                 => 'breakpoint',
								'type'                 => 'select',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-auto',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'choices'              => array(
									'xxl' => 'Screens less than 1440px',
									'xl'  => 'Screens less than 1280px',
									'lg'  => 'Screens less than 1024px',
									'md'  => 'Screens less than 768px',
									'sm'  => 'Screens less than 576px',
								),
								'default_value'        => 'lg',
								'allow_null'           => 1,
								'multiple'             => 0,
								'ui'                   => 0,
								'return_format'        => 'value',
								'placeholder'          => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
								'ajax'                 => 0,
							),
							array(
								'key'                  => 'field_6102f976f2867',
								'label'                => 'Navbar In Grid',
								'name'                 => 'in_grid',
								'type'                 => 'true_false',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-auto',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'message'              => 'Keep the whole navbar (including background color) in the main site grid',
								'default_value'        => 0,
								'ui'                   => 1,
								'ui_on_text'           => '',
								'ui_off_text'          => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'                  => 'field_6102f9bbf2868',
								'label'                => 'Navbar Content In Grid',
								'name'                 => 'in_grid_content',
								'type'                 => 'true_false',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-auto',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'message'              => 'Keep the navbar content in the main site grid',
								'default_value'        => 1,
								'ui'                   => 1,
								'ui_on_text'           => '',
								'ui_off_text'          => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'               => 'field_62cf37f830c38',
								'label'             => 'Mobile Menu Type',
								'name'              => 'mobile_menu_type',
								'type'              => 'button_group',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'           => array(
									'collapse'  => 'Drop Down',
									'offcanvas' => 'Offcanvas',
								),
								'allow_null'        => 0,
								'default_value'     => 'collapse : Drop Down',
								'layout'            => 'horizontal',
								'return_format'     => 'value',
							),
							array(
								'key'                  => 'field_6102fa15f2869',
								'label'                => 'Sticky Nav',
								'name'                 => 'sticky_nav',
								'type'                 => 'true_false',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-auto',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'message'              => '',
								'default_value'        => 0,
								'ui'                   => 1,
								'ui_on_text'           => '',
								'ui_off_text'          => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'               => 'field_61a810b0fee20',
								'label'             => 'Divider',
								'name'              => '',
								'type'              => 'admin_divider',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => 'spacer',
									'id'    => '',
								),
								'spacer'            => false,
							),
							array(
								'key'                  => 'field_6103008640fae',
								'label'                => 'Navbar CSS ID',
								'name'                 => 'navbar_css_id',
								'type'                 => 'text',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-4',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'default_value'        => '',
								'placeholder'          => '',
								'prepend'              => '',
								'append'               => '',
								'maxlength'            => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'                  => 'field_6103007540fad',
								'label'                => 'Navbar CSS Class',
								'name'                 => 'navbar_css_class',
								'type'                 => 'text',
								'instructions'         => '',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => 'col-md-8',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'default_value'        => '',
								'placeholder'          => '',
								'prepend'              => '',
								'append'               => '',
								'maxlength'            => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'               => 'field_61a810c8fee21',
								'label'             => 'Divider',
								'name'              => '',
								'type'              => 'admin_divider',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => 'spacer',
									'id'    => '',
								),
								'spacer'            => false,
							),
							array(
								'key'                 => 'field_6177228a97b1d',
								'label'               => 'Nabvar Toggle Icon',
								'name'                => 'toggle_icon',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_6177228a97b1e',
										'label'            => 'Icon to show when subnav is closed',
										'name'             => 'icon_closed',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-6',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61940d5ca41f6',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 1,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_6177228a97b1f',
										'label'            => 'Icon to show when subnav is open',
										'name'             => 'icon_opened',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-6',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61940d5ca41f6',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 1,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
								),
							),
							array(
								'key'               => 'field_61a81117fee23',
								'label'             => 'Divider',
								'name'              => '',
								'type'              => 'admin_divider',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => 'spacer',
									'id'    => '',
								),
								'spacer'            => false,
							),
							array(
								'key'                => 'field_5f9759d068313',
								'label'              => 'Items to add to the navbar',
								'name'               => 'order',
								'type'               => 'select',
								'instructions'       => '',
								'required'           => 0,
								'conditional_logic'  => 0,
								'wrapper'            => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'choices'            => array(
									'brand'  => 'Logo',
									'text'   => 'Custom Text',
									'search' => 'Search Bar',
									'toggle' => 'Responsive Toggle',
									'navbar' => 'The menu',
								),
								'default_value'      => array(
									0 => 'brand',
									1 => 'navbar',
									2 => 'toggle',
								),
								'allow_null'         => 1,
								'multiple'           => 1,
								'ui'                 => 1,
								'ajax'               => 0,
								'return_format'      => 'value',
								'allow_custom'       => 0,
								'placeholder'        => '',
								'search_placeholder' => '',
							),
							array(
								'key'                 => 'field_5f975b3668317',
								'label'               => 'Custom Text',
								'name'                => 'text',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => array(
									array(
										array(
											'field'    => 'field_5f9759d068313',
											'operator' => '==contains',
											'value'    => 'text',
										),
									),
								),
								'wrapper'             => array(
									'width' => '',
									'class' => 'col-12 bg-light label-md',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 0,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'           => 'field_61a14d1cf1bf9',
										'label'         => 'Content',
										'name'          => 'content',
										'type'          => 'wysiwyg',
										'instructions'  => '',
										'required'      => 0,
										'conditional_logic' => 0,
										'wrapper'       => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'default_value' => '',
										'tabs'          => 'text',
										'media_upload'  => 1,
										'toolbar'       => 'full',
										'delay'         => 0,
									),
								),
							),
							array(
								'key'                 => 'field_61a14dd0f1bfc',
								'label'               => 'Logo',
								'name'                => 'brand',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => array(
									array(
										array(
											'field'    => 'field_5f9759d068313',
											'operator' => '==contains',
											'value'    => 'brand',
										),
									),
								),
								'wrapper'             => array(
									'width' => '',
									'class' => 'col-12 bg-light label-md',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_61a14dfbf1bfd',
										'label'            => 'Header Logo Attributes',
										'name'             => 'atts',
										'type'             => 'group',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'label-none',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'layout'           => 'block',
										'acfe_seamless_style' => 1,
										'acfe_group_modal' => 0,
										'sub_fields'       => array(
											array(
												'key'      => 'field_61a14e1cf1bfe',
												'label'    => 'Classes',
												'name'     => 'class',
												'type'     => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'placeholder' => '',
												'prepend'  => '',
												'append'   => '',
												'maxlength' => '',
											),
										),
									),
								),
							),
							array(
								'key'                 => 'field_61a14e3ff1bff',
								'label'               => 'Search',
								'name'                => 'search',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => array(
									array(
										array(
											'field'    => 'field_5f9759d068313',
											'operator' => '==contains',
											'value'    => 'search',
										),
									),
								),
								'wrapper'             => array(
									'width' => '',
									'class' => 'col-12 bg-light mt-3 label-md',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_61a14e3ff1c00',
										'label'            => 'Field Attributes',
										'name'             => 'input',
										'type'             => 'group',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'layout'           => 'block',
										'acfe_seamless_style' => 1,
										'acfe_group_modal' => 0,
										'sub_fields'       => array(
											array(
												'key'      => 'field_61a7f69588d5b',
												'label'    => 'Atts',
												'name'     => 'atts',
												'type'     => 'group',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => 'label-none',
													'id' => '',
												),
												'layout'   => 'block',
												'acfe_seamless_style' => 1,
												'acfe_group_modal' => 0,
												'sub_fields' => array(
													array(
														'key' => 'field_61a7f6a088d5c',
														'label' => 'Placeholder',
														'name' => 'placeholder',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => 'col-md-4',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => 'Search',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
													array(
														'key' => 'field_61a7f6bc88d5d',
														'label' => 'CSS Classes',
														'name' => 'class',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => 'col-md-8',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
												),
											),
										),
									),
									array(
										'key'          => 'field_61a7fbd818f44',
										'label'        => 'Divider',
										'name'         => '',
										'type'         => 'admin_divider',
										'instructions' => '',
										'required'     => 0,
										'conditional_logic' => 0,
										'wrapper'      => array(
											'width' => '',
											'class' => 'divider',
											'id'    => '',
										),
										'spacer'       => false,
									),
									array(
										'key'              => 'field_61a823589c66e',
										'label'            => 'Field Wrapper Attributes',
										'name'             => 'input_wrapper',
										'type'             => 'group',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'layout'           => 'block',
										'acfe_seamless_style' => 1,
										'acfe_group_modal' => 0,
										'sub_fields'       => array(
											array(
												'key'      => 'field_61a823589c66f',
												'label'    => 'Atts',
												'name'     => 'atts',
												'type'     => 'group',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => 'label-none',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'layout'   => 'block',
												'acfe_seamless_style' => 1,
												'acfe_group_modal' => 0,
												'sub_fields' => array(
													array(
														'key' => 'field_61a823589c671',
														'label' => 'CSS Classes',
														'name' => 'class',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => 'col-md-8',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
														'show_column' => 0,
														'show_column_sortable' => 0,
														'show_column_weight' => 1000,
														'allow_quickedit' => 0,
														'allow_bulkedit' => 0,
													),
												),
											),
										),
									),
									array(
										'key'            => 'field_61a8237c9c672',
										'label'          => 'Divider',
										'name'           => '',
										'type'           => 'admin_divider',
										'instructions'   => '',
										'required'       => 0,
										'conditional_logic' => 0,
										'wrapper'        => array(
											'width' => '',
											'class' => 'divider',
											'id'    => '',
										),
										'acfe_save_meta' => 0,
										'spacer'         => 0,
									),
									array(
										'key'              => 'field_61a7f62c88d56',
										'label'            => 'Label Attributes',
										'name'             => 'label',
										'type'             => 'group',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'layout'           => 'block',
										'acfe_seamless_style' => 1,
										'acfe_group_modal' => 0,
										'sub_fields'       => array(
											array(
												'key'      => 'field_61a7f62c88d58',
												'label'    => 'Text',
												'name'     => 'content',
												'type'     => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'acfe_save_meta' => 0,
												'default_value' => '',
												'placeholder' => '',
												'prepend'  => '',
												'append'   => '',
												'maxlength' => '',
												'show_column' => 0,
												'show_column_sortable' => 0,
												'show_column_weight' => 1000,
												'allow_quickedit' => 0,
												'allow_bulkedit' => 0,
											),
											array(
												'key'      => 'field_61a7f64f88d59',
												'label'    => 'Atts',
												'name'     => 'atts',
												'type'     => 'group',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => 'label-none',
													'id' => '',
												),
												'layout'   => 'block',
												'acfe_seamless_style' => 1,
												'acfe_group_modal' => 0,
												'sub_fields' => array(
													array(
														'key' => 'field_61a7f66088d5a',
														'label' => 'CSS Class',
														'name' => 'class',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => '',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
												),
											),
										),
									),
									array(
										'key'          => 'field_61a7fc0318f45',
										'label'        => 'Divider',
										'name'         => '',
										'type'         => 'admin_divider',
										'instructions' => '',
										'required'     => 0,
										'conditional_logic' => 0,
										'wrapper'      => array(
											'width' => '',
											'class' => 'divider',
											'id'    => '',
										),
										'spacer'       => false,
									),
									array(
										'key'              => 'field_61a14e92f1c02',
										'label'            => 'Button Attributes',
										'name'             => 'button',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61a155444fe0e',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 1,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'          => 'field_61a7fc0d18f46',
										'label'        => 'Divider',
										'name'         => '',
										'type'         => 'admin_divider',
										'instructions' => '',
										'required'     => 0,
										'conditional_logic' => 0,
										'wrapper'      => array(
											'width' => '',
											'class' => 'divider',
											'id'    => '',
										),
										'spacer'       => false,
									),
									array(
										'key'              => 'field_61a7f537182a2',
										'label'            => 'Form Attributes',
										'name'             => 'form',
										'type'             => 'group',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => '',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'layout'           => 'block',
										'acfe_seamless_style' => 1,
										'acfe_group_modal' => 0,
										'sub_fields'       => array(
											array(
												'key'      => 'field_61a81e5ef893b',
												'label'    => 'Atts',
												'name'     => 'atts',
												'type'     => 'group',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper'  => array(
													'width' => '',
													'class' => 'label-none',
													'id' => '',
												),
												'layout'   => 'block',
												'acfe_seamless_style' => 1,
												'acfe_group_modal' => 0,
												'sub_fields' => array(
													array(
														'key' => 'field_61a7f71d88d5e',
														'label' => 'CSS ID',
														'name' => 'id',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => 'col-md-4',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
													),
													array(
														'key' => 'field_61a7f548182a3',
														'label' => 'CSS Classes',
														'name' => 'class',
														'type' => 'text',
														'instructions' => '',
														'required' => 0,
														'conditional_logic' => 0,
														'wrapper' => array(
															'width' => '',
															'class' => 'col-md-8',
															'id' => '',
														),
														'acfe_save_meta' => 0,
														'default_value' => '',
														'placeholder' => '',
														'prepend' => '',
														'append' => '',
														'maxlength' => '',
														'show_column' => 0,
														'show_column_sortable' => 0,
														'show_column_weight' => 1000,
														'allow_quickedit' => 0,
														'allow_bulkedit' => 0,
													),
												),
											),
										),
									),
								),
							),
						),
					),
					array(
						'key'               => 'field_61a7fcde36fb8',
						'label'             => 'Divider',
						'name'              => '',
						'type'              => 'admin_divider',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => 'spacer',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'spacer'            => false,
					),
					array(
						'key'                  => 'field_5f975ac568316',
						'label'                => 'Submenu Type',
						'name'                 => 'toggle_type',
						'type'                 => 'select',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'acfe_save_meta'       => 0,
						'choices'              => array(
							'indented' => 'Bulleted list of links',
							'collapse' => 'Accordion Style',
							'dropdown' => 'Dropdown Style',
							'tab'      => 'Tab Style',
						),
						'default_value'        => false,
						'allow_null'           => 1,
						'multiple'             => 0,
						'ui'                   => 0,
						'return_format'        => 'value',
						'placeholder'          => '',
						'show_column'          => 0,
						'show_column_sortable' => 0,
						'show_column_weight'   => 1000,
						'allow_quickedit'      => 0,
						'allow_bulkedit'       => 0,
						'ajax'                 => 0,
					),
					array(
						'key'               => 'field_628e6fd8e39f1',
						'label'             => 'Show Dropdown on Hover?',
						'name'              => 'dropdown_hover',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => array(
							array(
								array(
									'field'    => 'field_5f975ac568316',
									'operator' => '==',
									'value'    => 'dropdown',
								),
							),
						),
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'ui'                => 1,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
					),
					array(
						'key'                 => 'field_617721f57445c',
						'label'               => 'Toggle Icon',
						'name'                => 'toggle_icon',
						'type'                => 'group',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => array(
							array(
								array(
									'field'    => 'field_5f975ac568316',
									'operator' => '==',
									'value'    => 'collapse',
								),
							),
							array(
								array(
									'field'    => 'field_5f975ac568316',
									'operator' => '==',
									'value'    => 'dropdown',
								),
							),
						),
						'wrapper'             => array(
							'width' => '',
							'class' => 'label-none',
							'id'    => '',
						),
						'acfe_save_meta'      => 0,
						'layout'              => 'block',
						'acfe_seamless_style' => 1,
						'acfe_group_modal'    => 0,
						'sub_fields'          => array(
							array(
								'key'                 => 'field_617721f57445d',
								'label'               => 'Icon to show when subnav is closed',
								'name'                => 'icon_closed',
								'type'                => 'clone',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => 'col-md-6',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'clone'               => array(
									0 => 'field_61940d5ca41f6',
								),
								'display'             => 'group',
								'layout'              => 'block',
								'prefix_label'        => 0,
								'prefix_name'         => 1,
								'acfe_seamless_style' => 1,
								'acfe_clone_modal'    => 0,
							),
							array(
								'key'                 => 'field_617721f57445e',
								'label'               => 'Icon to show when subnav is open',
								'name'                => 'icon_opened',
								'type'                => 'clone',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => 'col-md-6',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'clone'               => array(
									0 => 'field_61940d5ca41f6',
								),
								'display'             => 'group',
								'layout'              => 'block',
								'prefix_label'        => 0,
								'prefix_name'         => 1,
								'acfe_seamless_style' => 1,
								'acfe_clone_modal'    => 0,
							),
						),
					),
					array(
						'key'               => 'field_628e702ce39f2',
						'label'             => 'Divider',
						'name'              => '',
						'type'              => 'admin_divider',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => 'spacer',
							'id'    => '',
						),
						'acfe_save_meta'    => 0,
						'spacer'            => 0,
					),
					array(
						'key'                 => 'field_619448221dcfb',
						'label'               => 'Nav Item Options',
						'name'                => 'item_options',
						'type'                => 'group',
						'instructions'        => '',
						'required'            => 0,
						'conditional_logic'   => 0,
						'wrapper'             => array(
							'width' => '',
							'class' => 'label-lg border w-100 p-3',
							'id'    => '',
						),
						'acfe_save_meta'      => 0,
						'layout'              => 'block',
						'acfe_seamless_style' => 1,
						'acfe_group_modal'    => 0,
						'sub_fields'          => array(
							array(
								'key'                  => 'field_619447d41dcfa',
								'label'                => 'Classes',
								'name'                 => 'class',
								'type'                 => 'text',
								'instructions'         => 'Will be applied to all menu items',
								'required'             => 0,
								'conditional_logic'    => 0,
								'wrapper'              => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'acfe_save_meta'       => 0,
								'default_value'        => '',
								'placeholder'          => '',
								'prepend'              => '',
								'append'               => '',
								'maxlength'            => '',
								'show_column'          => 0,
								'show_column_sortable' => 0,
								'show_column_weight'   => 1000,
								'allow_quickedit'      => 0,
								'allow_bulkedit'       => 0,
							),
							array(
								'key'                 => 'field_61ad0397fd433',
								'label'               => 'Style Options',
								'name'                => 'styles',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => 'label-none',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_61ad0397fd434',
										'label'            => 'Background Color',
										'name'             => 'background_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61772ca5bb3c1',
										),
										'display'          => 'group',
										'layout'           => '',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad0397fd435',
										'label'            => 'Text Color',
										'name'             => 'text_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfdb9f7a54',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad0397fd436',
										'label'            => 'Border Color',
										'name'             => 'border_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfe12f7a57',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
								),
							),
							array(
								'key'               => 'field_6244932d7ad19',
								'label'             => 'Divider',
								'name'              => '',
								'type'              => 'admin_divider',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'spacer'            => 0,
							),
							array(
								'key'                 => 'field_61ad148d289ba',
								'label'               => 'Hover Options',
								'name'                => 'hover',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => 'bg-light',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_61ad148d289bb',
										'label'            => 'Background Color',
										'name'             => 'background_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61772ca5bb3c1',
										),
										'display'          => 'group',
										'layout'           => '',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad148d289bc',
										'label'            => 'Text Color',
										'name'             => 'text_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfdb9f7a54',
										),
										'display'          => 'group',
										'layout'           => '',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad148d289bd',
										'label'            => 'Border Color',
										'name'             => 'border_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfe12f7a57',
										),
										'display'          => 'group',
										'layout'           => '',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
										'acfe_clone_modal_close' => 0,
										'acfe_clone_modal_button' => '',
										'acfe_clone_modal_size' => 'large',
									),
								),
							),
							array(
								'key'                 => 'field_61ad14a0289be',
								'label'               => 'Active Options',
								'name'                => 'active',
								'type'                => 'group',
								'instructions'        => '',
								'required'            => 0,
								'conditional_logic'   => 0,
								'wrapper'             => array(
									'width' => '',
									'class' => 'bg-light',
									'id'    => '',
								),
								'acfe_save_meta'      => 0,
								'layout'              => 'block',
								'acfe_seamless_style' => 1,
								'acfe_group_modal'    => 0,
								'sub_fields'          => array(
									array(
										'key'              => 'field_61ad14a0289bf',
										'label'            => 'Background Color',
										'name'             => 'background_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61772ca5bb3c1',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad14a0289c0',
										'label'            => 'Text Color',
										'name'             => 'text_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfdb9f7a54',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
									),
									array(
										'key'              => 'field_61ad14a0289c1',
										'label'            => 'Border Color',
										'name'             => 'border_color',
										'type'             => 'clone',
										'instructions'     => '',
										'required'         => 0,
										'conditional_logic' => 0,
										'wrapper'          => array(
											'width' => '',
											'class' => 'col-md-4',
											'id'    => '',
										),
										'acfe_save_meta'   => 0,
										'clone'            => array(
											0 => 'field_61acfe12f7a57',
										),
										'display'          => 'group',
										'layout'           => 'block',
										'prefix_label'     => 0,
										'prefix_name'      => 0,
										'acfe_seamless_style' => 1,
										'acfe_clone_modal' => 0,
										'acfe_clone_modal_close' => 0,
										'acfe_clone_modal_button' => '',
										'acfe_clone_modal_size' => 'large',
									),
								),
							),
						),
					),
				),
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'nav_menu',
					'operator' => '==',
					'value'    => 'all',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen'        => '',
		'active'                => true,
		'description'           => '',
		'show_in_rest'          => 0,
		'acfe_display_title'    => '',
		'acfe_autosync'         => array(
			0 => 'php',
		),
		'acfe_form'             => 0,
		'acfe_meta'             => '',
		'acfe_note'             => '',
		'acfe_categories'       => array(
			'plugin' => 'Plugin',
		),
		'modified'              => 1657748221,
	) );

endif;
