<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_plugin_settings',
	'title' => 'Plugin Settings',
	'fields' => array(
		array(
			'key' => 'field_5fa458207dcfb',
			'label' => 'Plugin',
			'name' => 'plugin',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_permissions' => '',
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5fa4363b2b632',
					'label' => 'Add Custom Post Types',
					'name' => 'cpt',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => 'field_5fa4368b2b633',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Custom Post type',
					'sub_fields' => array(
						array(
							'key' => 'field_5fa436d32b636',
							'label' => 'Labels',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5fa4368b2b633',
							'label' => 'Singular Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-md-4',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa436ab2b634',
							'label' => 'Plural Label',
							'name' => 'plural',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-md-4',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa436bf2b635',
							'label' => 'Menu Label',
							'name' => 'menu',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-md-4',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa436ec2b637',
							'label' => 'Urls',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5fa4373c2b639',
							'label' => 'Customize Urls',
							'name' => 'customize',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa4725394adf',
							'label' => 'Rewrite',
							'name' => 'rewrite',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fa4373c2b639',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto flex-fill',
								'id' => '',
							),
							'acfe_permissions' => '',
							'layout' => 'block',
							'acfe_seamless_style' => 1,
							'acfe_group_modal' => 0,
							'sub_fields' => array(
								array(
									'key' => 'field_5fa437102b638',
									'label' => 'Post Url Slug',
									'name' => 'slug',
									'type' => 'acfe_slug',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto flex-fill',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => 'sitename.com/',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5fa437642b63a',
									'label' => 'With Front',
									'name' => 'with_front',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto',
										'id' => '',
									),
									'acfe_permissions' => '',
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
							),
						),
						array(
							'key' => 'field_5fa4379e2b63c',
							'label' => 'Options',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5fa437b72b63d',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 2,
							'new_lines' => '',
							'acfe_textarea_code' => 0,
						),
						array(
							'key' => 'field_5fa437cc2b63e',
							'label' => 'Supports',
							'name' => 'supports',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'title' => 'Title',
								'editor' => 'Editor',
								'thumbnail' => 'Featured Image',
								'comments' => 'Comments',
								'trackbacks' => 'Trackbacks',
								'revisions' => 'Revisions',
								'custom-fields' => 'Custom Fields (non-acf)',
								'page-attributes' => 'Page Attributes',
								'post-formats' => 'Post Formats',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'horizontal',
							'toggle' => 1,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_5fa4385f2b63f',
							'label' => 'Associated Taxonomies',
							'name' => 'taxonomies',
							'type' => 'acfe_taxonomies',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'taxonomy' => '',
							'field_type' => 'checkbox',
							'default_value' => '',
							'return_format' => 'name',
							'layout' => 'horizontal',
							'toggle' => 1,
							'allow_custom' => 0,
							'multiple' => 0,
							'allow_null' => 0,
							'choices' => array(
							),
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_5fa438852b640',
							'label' => 'Hierarchical',
							'name' => 'hierarchical',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa438ad2b641',
							'label' => 'Has Archive',
							'name' => 'has_archive',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa438c72b642',
							'label' => 'Custom Archive Slug',
							'name' => 'archive_slug',
							'type' => 'acfe_slug',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5fa438ad2b641',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto flex-fill',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa439052b643',
							'label' => 'Exclude From Search',
							'name' => 'exclude_from_search',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa4391d2b644',
							'label' => 'Enable Export',
							'name' => 'can_export',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 1,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa43a762b647',
							'label' => 'Use Gutenberg Editor',
							'name' => 'show_in_rest',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa4398b2b646',
							'label' => 'Admin Menu Position',
							'name' => 'menu_position',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								5 => '5 - below Posts',
								10 => '10 - below Posts',
								15 => '15 - below Links',
								20 => '20 - below Pages',
								25 => '25 - below Comments',
								60 => '60 - below first separator',
								65 => '65 - below Plugins',
								70 => '70 - below Users',
								75 => '75 - below Tools',
								80 => '80 - below Settings',
								100 => '100 - below second separator',
							),
							'default_value' => false,
							'allow_null' => 1,
							'multiple' => 0,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'allow_custom' => 1,
							'placeholder' => '',
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_5fa4393f2b645',
							'label' => 'Admin Sidebar Icon',
							'name' => 'menu_icon',
							'type' => 'text',
							'instructions' => 'Post type icon. Use <a href="https://developer.wordpress.org/resource/dashicons/" target="_blank">dashicon</a> name or full icon URL (http://.../icon.png).',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'rwp_plugin',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => array(
		'acfcloneindex' => array(
			'acfe_meta_key' => '',
			'acfe_meta_value' => '',
		),
	),
	'acfe_note' => '',
	'acfe_categories' => array(
		'plugin' => 'Plugin',
	),
	'modified' => 1608571527,
));

endif;