<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_company_info',
	'title' => 'Company Info',
	'fields' => array(
		array(
			'key' => 'field_5dd4065a2b746',
			'label' => 'Company Info',
			'name' => 'company_info',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5dd3193dfa71f',
					'label' => 'Search Appearance',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_company_image',
					'label' => 'Company Image',
					'name' => 'company_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'col-lg-auto',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 1920,
					'max_height' => 1080,
					'max_size' => '',
					'mime_types' => 'png,jpg,jpeg',
				),
				array(
					'key' => 'field_5fa48ae8162c1',
					'label' => 'Company Logo',
					'name' => 'company_logo',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'col-lg-auto',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => 1920,
					'max_height' => 1080,
					'max_size' => '',
					'mime_types' => 'png,jpg,jpeg',
					'uploader' => 'wp',
				),
				array(
					'key' => 'field_5dd2e0ee10fa5',
					'label' => 'Company Name',
					'name' => 'company_name',
					'type' => 'text',
					'instructions' => 'Defaults to title of site',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'col-lg-auto',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fa48a7f162bf',
					'label' => 'Schema Type',
					'name' => 'schema_type',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'col-lg-auto',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => 'Organization',
					'placeholder' => 'Organization',
					'prepend' => 'https://schema.org/',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5fa48aa9162c0',
					'label' => 'Additional Type',
					'name' => 'additional_type',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'col-lg-auto',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5dd30b6c14567',
					'label' => 'Locations',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5dd30d7788540',
					'label' => 'Locations',
					'name' => 'locations',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'large-label',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => 'field_5dd30ddf88542',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Location',
					'sub_fields' => array(
						array(
							'key' => 'field_5fa585b46b197',
							'label' => 'Search Appearance',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5dd30ddf88542',
							'label' => 'Location Name',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_sublocation_image',
							'label' => 'Location Image',
							'name' => 'search_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5dd30df188543',
							'label' => 'Location Url',
							'name' => 'url',
							'type' => 'link',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto flex-fill',
								'id' => '',
							),
							'return_format' => 'array',
						),
						array(
							'key' => 'field_5dd314e1cdc46',
							'label' => 'Location Description',
							'name' => 'description',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-12',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => '',
						),
						array(
							'key' => 'field_5dd31509cdc48',
							'label' => 'Schema Type',
							'name' => 'schema_type',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'default_value' => 'LocalBusiness',
							'placeholder' => 'LocalBusiness',
							'prepend' => 'https://schema.org/',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5dd3150ccdc49',
							'label' => 'Additional Type',
							'name' => 'additional_type',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5fa585c56b198',
							'label' => 'Location Info',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5dd30e2288544',
							'label' => 'Address',
							'name' => 'address',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5dd311c34d2f1',
									'label' => 'Street Address',
									'name' => 'street',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto flex-fill',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5dd311cf4d2f2',
									'label' => 'Unit/Suite',
									'name' => 'unit',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_sub_address_line_1_divider',
									'label' => 'Divider',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'divider',
										'id' => '',
									),
									'message' => '',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_5dd311da4d2f3',
									'label' => 'City/Locality',
									'name' => 'locality',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-3',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5dd311eb4d2f4',
									'label' => 'State/Region',
									'name' => 'region',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-3',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5dd311f84d2f5',
									'label' => 'Postal Code',
									'name' => 'postal',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-3',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5dd311ff4d2f6',
									'label' => 'Country',
									'name' => 'country',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-3',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_sub_address_line_2_divider',
									'label' => 'Divider',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'divider',
										'id' => '',
									),
									'message' => '',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_5dd312054d2f7',
									'label' => 'Latitude',
									'name' => 'latitude',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
								),
								array(
									'key' => 'field_5dd312134d2f8',
									'label' => 'Longitude',
									'name' => 'longitude',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
								),
								array(
									'key' => 'field_5dd3121a4d2f9',
									'label' => 'Map Url',
									'name' => 'map_url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto flex-fill',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
							),
						),
						array(
							'key' => 'field_5ebf325b6e7a9',
							'label' => 'Operating Hours',
							'name' => 'hours',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'acfe_repeater_stylised_button' => 0,
							'collapsed' => 'field_5ebf325b6e7ab',
							'min' => 0,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Schedule',
							'sub_fields' => array(
								array(
									'key' => 'field_5ebf325b6e7ab',
									'label' => 'Schedule Title',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-lg-auto flex-fill',
										'id' => '',
									),
									'acfe_permissions' => '',
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ebf325b6e7ac',
									'label' => 'Times',
									'name' => 'times',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'col-12 seamless',
										'id' => '',
									),
									'acfe_permissions' => '',
									'acfe_repeater_stylised_button' => 0,
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'block',
									'button_label' => 'Add Time Slot',
									'sub_fields' => array(
										array(
											'key' => 'field_5ebf325b6e7ad',
											'label' => 'All Day',
											'name' => 'all_day',
											'type' => 'true_false',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => 'col-auto',
												'id' => '',
											),
											'acfe_permissions' => '',
											'message' => '',
											'default_value' => 0,
											'ui' => 1,
											'ui_on_text' => '',
											'ui_off_text' => '',
										),
										array(
											'key' => 'field_5fa9b03450f47',
											'label' => 'Time Type',
											'name' => 'time_type',
											'type' => 'button_group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => 'col-auto',
												'id' => '',
											),
											'acfe_permissions' => '',
											'choices' => array(
												'open' => 'Open',
												'closed' => 'Closed',
											),
											'allow_null' => 0,
											'default_value' => 'open',
											'layout' => 'horizontal',
											'return_format' => 'value',
										),
										array(
											'key' => 'field_5ebf325b6e7af',
											'label' => 'Start Time',
											'name' => 'start',
											'type' => 'time_picker',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7ad',
														'operator' => '!=',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => 'col-md-auto flex-fill',
												'id' => '',
											),
											'display_format' => 'g:i a',
											'return_format' => 'H:i',
										),
										array(
											'key' => 'field_5fa9afbe50f46',
											'label' => 'Separator',
											'name' => 'separator',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7ad',
														'operator' => '!=',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => 'col-md-auto',
												'id' => '',
											),
											'acfe_permissions' => '',
											'default_value' => '–',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5ebf325b6e7b0',
											'label' => 'End Time',
											'name' => 'end',
											'type' => 'time_picker',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7ad',
														'operator' => '!=',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => 'col-md-auto flex-fill',
												'id' => '',
											),
											'display_format' => 'g:i a',
											'return_format' => 'H:i',
										),
										array(
											'key' => 'field_5f274f36fea54',
											'label' => 'Format',
											'name' => 'format',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7ad',
														'operator' => '!=',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => 'col-md-auto',
												'id' => '',
											),
											'acfe_permissions' => '',
											'default_value' => 'g:i a',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5fa9b08c50f48',
											'label' => 'All Day Label',
											'name' => 'all_day_label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7ad',
														'operator' => '==',
														'value' => '1',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => 'col-auto flex-fill',
												'id' => '',
											),
											'acfe_permissions' => '',
											'default_value' => 'All Day',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
								),
								array(
									'key' => 'field_5fa9b10350f49',
									'label' => 'Days',
									'name' => 'days',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_permissions' => '',
									'layout' => 'block',
									'acfe_seamless_style' => 1,
									'acfe_group_modal' => 0,
									'sub_fields' => array(
										array(
											'key' => 'field_5ebf325b6e7aa',
											'label' => 'Schedule Type',
											'name' => 'day_type',
											'type' => 'select',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => 'col-lg-auto',
												'id' => '',
											),
											'acfe_permissions' => '',
											'choices' => array(
												'daily' => 'Every day',
												'weekly' => 'Certain days of the week',
												'monthly' => 'Certain days of the month',
												'custom' => 'Custom Dates',
											),
											'default_value' => false,
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 0,
											'return_format' => 'value',
											'ajax' => 0,
											'placeholder' => '',
										),
										array(
											'key' => 'field_5fa9b1dd6e474',
											'label' => 'Weekly',
											'name' => 'weekly',
											'type' => 'button_group',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7aa',
														'operator' => '==',
														'value' => 'weekly',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'acfe_permissions' => '',
											'choices' => array(
												'Sunday' => 'Sunday',
												'Monday' => 'Monday',
												'Tuesday' => 'Tuesday',
												'Wednesday' => 'Wednesday',
												'Thursday' => 'Thursday',
												'Friday' => 'Friday',
												'Saturday' => 'Saturday',
											),
											'allow_null' => 0,
											'default_value' => '',
											'layout' => 'horizontal',
											'return_format' => 'value',
										),
										array(
											'key' => 'field_5fa9b3bf6e475',
											'label' => 'Monthly',
											'name' => 'monthly',
											'type' => 'select',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7aa',
														'operator' => '==',
														'value' => 'monthly',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'acfe_permissions' => '',
											'choices' => array(
												1 => '1',
												2 => '2',
												3 => '3',
												4 => '4',
												5 => '5',
												6 => '6',
												7 => '7',
												8 => '8',
												9 => '9',
												10 => '10',
												11 => '11',
												12 => '12',
												13 => '13',
												14 => '14',
												15 => '15',
												16 => '16',
												17 => '17',
												18 => '18',
												19 => '19',
												20 => '20',
												21 => '21',
												22 => '22',
												23 => '23',
												24 => '24',
												25 => '25',
												26 => '26',
												27 => '27',
												28 => '28',
												29 => '29',
												30 => '30',
												31 => '31',
											),
											'default_value' => array(
											),
											'allow_null' => 0,
											'multiple' => 1,
											'ui' => 1,
											'ajax' => 0,
											'return_format' => 'value',
											'allow_custom' => 0,
											'placeholder' => '',
											'search_placeholder' => '',
										),
										array(
											'key' => 'field_5fa9b57b6e476',
											'label' => 'Custom Dates',
											'name' => 'custom',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ebf325b6e7aa',
														'operator' => '==',
														'value' => 'custom',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'acfe_permissions' => '',
											'acfe_repeater_stylised_button' => 0,
											'collapsed' => 'field_5fa9b5a96e477',
											'min' => 0,
											'max' => 0,
											'layout' => 'block',
											'button_label' => 'Add Custom Date',
											'sub_fields' => array(
												array(
													'key' => 'field_5fa9b5a96e477',
													'label' => 'Custom Dates Label',
													'name' => 'label',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto flex-fill',
														'id' => '',
													),
													'acfe_permissions' => '',
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5fa9b67e6e47d',
													'label' => 'Display Label',
													'name' => 'display_label',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto',
														'id' => '',
													),
													'acfe_permissions' => '',
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5fa9b6e46e47f',
													'label' => 'Repeats Annually',
													'name' => 'repeats_annually',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-auto',
														'id' => '',
													),
													'acfe_permissions' => '',
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5fa9b6496e47c',
													'label' => 'Format',
													'name' => 'format',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto',
														'id' => '',
													),
													'acfe_permissions' => '',
													'default_value' => 'F j, Y',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5fa9b8852aafd',
													'label' => 'Divider',
													'name' => '',
													'type' => 'message',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'divider',
														'id' => '',
													),
													'acfe_permissions' => '',
													'message' => '',
													'new_lines' => 'wpautop',
													'esc_html' => 0,
												),
												array(
													'key' => 'field_5fa9b5fc6e479',
													'label' => 'Add End Date',
													'name' => 'add_end_date',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-auto',
														'id' => '',
													),
													'acfe_permissions' => '',
													'message' => '',
													'default_value' => 0,
													'ui' => 1,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5fa9b5d06e478',
													'label' => 'Start Date',
													'name' => 'start_date',
													'type' => 'date_picker',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto flex-fill',
														'id' => '',
													),
													'acfe_permissions' => '',
													'display_format' => 'F j, Y',
													'return_format' => 'Ymd',
													'first_day' => 0,
												),
												array(
													'key' => 'field_5fa9b6096e47a',
													'label' => 'Separator',
													'name' => 'separator',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5fa9b5fc6e479',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto',
														'id' => '',
													),
													'acfe_permissions' => '',
													'default_value' => '–',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5fa9b6336e47b',
													'label' => 'End Date',
													'name' => 'end_date',
													'type' => 'date_picker',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5fa9b5fc6e479',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '',
														'class' => 'col-md-auto flex-fill',
														'id' => '',
													),
													'acfe_permissions' => '',
													'display_format' => 'F j, Y',
													'return_format' => 'Ymd',
													'first_day' => 0,
												),
											),
										),
									),
								),
							),
						),
						array(
							'key' => 'field_5fa585db6b199',
							'label' => 'Contact Info',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5fa5854c6b195',
							'label' => 'Add Custom Socials for this location?',
							'name' => 'add_location_socials',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'col-12',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5dd313ef310ca',
							'label' => 'Social Profiles',
							'name' => 'socials',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
									array(
										'field' => 'field_5fa5854c6b195',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5e72824b5255f',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
						array(
							'key' => 'field_5fa5856c6b196',
							'label' => 'Add Custom Contact Info for this location?',
							'name' => 'add_location_contact_info',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'col-12',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa585036b194',
							'label' => 'Phone',
							'name' => 'phone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
									array(
										'field' => 'field_5fa5856c6b196',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5ebf3e8f5ed9a',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
						array(
							'key' => 'field_5fa5cd7a86eba',
							'label' => 'Email',
							'name' => 'email',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
									array(
										'field' => 'field_5fa5856c6b196',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5ebf3e955eda2',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
						array(
							'key' => 'field_5fa5cd8c86ebb',
							'label' => 'Fax',
							'name' => 'fax',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5dd30d7788540',
										'operator' => '>',
										'value' => '1',
									),
									array(
										'field' => 'field_5fa5856c6b196',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5ebf3e935ed9e',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
					),
				),
				array(
					'key' => 'field_5dd2e26c84fb8',
					'label' => 'Contact Information',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'top',
					'endpoint' => 0,
				),
				array(
					'key' => 'field_5dd30a802d432',
					'label' => 'Social Profiles',
					'name' => 'socials',
					'type' => 'clone',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'large-label',
						'id' => '',
					),
					'clone' => array(
						0 => 'field_5e72824b5255f',
					),
					'display' => 'group',
					'layout' => 'block',
					'prefix_label' => 1,
					'prefix_name' => 0,
					'acfe_seamless_style' => 0,
					'acfe_clone_modal' => 0,
				),
				array(
					'key' => 'field_5ebf3e955eda2',
					'label' => 'Email',
					'name' => 'email',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'large-label',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => 'field_5fa5b6a75fc11',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Email',
					'sub_fields' => array(
						array(
							'key' => 'field_5fa5b6a75fc11',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-md-auto flex-fill',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa5c8e00b4ab',
							'label' => 'Display Label',
							'name' => 'display_label',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa5b6b75fc12',
							'label' => 'Email',
							'name' => 'email',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5fa5b5713cdec',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
				),
				array(
					'key' => 'field_5ebf3e8f5ed9a',
					'label' => 'Phone',
					'name' => 'phone',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'large-label',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => 'field_5fa5b6fb5fc13',
					'min' => 0,
					'max' => 0,
					'layout' => 'block',
					'button_label' => 'Add Phone',
					'sub_fields' => array(
						array(
							'key' => 'field_5fa5b6fb5fc13',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-md-auto flex-fill',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5fa98ae278f4f',
							'label' => 'Display Label',
							'name' => 'display_label',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5fa5b70e5fc14',
							'label' => 'Phone',
							'name' => 'phone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'clone' => array(
								0 => 'field_5fa5b61d3cdfa',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
				),
				array(
					'key' => 'field_5ebf3e935ed9e',
					'label' => 'Fax',
					'name' => 'fax',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => 'large-label',
						'id' => '',
					),
					'acfe_permissions' => '',
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5ebf3e935ed9f',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto flex-fill',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ebf3e935eda0',
							'label' => 'Number',
							'name' => 'content',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto flex-fill',
								'id' => '',
							),
							'acfe_permissions' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ebf3e935eda1',
							'label' => 'Is Default',
							'name' => 'default',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-lg-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5f277f6096145',
							'label' => 'Display Label',
							'name' => 'display_label',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'col-auto',
								'id' => '',
							),
							'acfe_permissions' => '',
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'rwp_company_info',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'plugin' => 'Plugin',
	),
	'modified' => 1611790824,
));

endif;