<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_nav_options',
	'title' => 'Nav Options',
	'fields' => array(
		array(
			'key' => 'field_5fe15b0a697ca',
			'label' => 'Nav Options',
			'name' => 'nav_options',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'acfe_seamless_style' => 1,
			'acfe_group_modal' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_5f97580f6830d',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'nav' => 'Basic navigation list',
						'navbar' => 'A site navigation bar',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f97588b6830e',
					'label' => 'Direction',
					'name' => 'direction',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'vertical' => 'Vertical',
						'horizontal' => 'Horizontal',
					),
					'allow_null' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array(
					'key' => 'field_5f9758b86830f',
					'label' => 'Theme',
					'name' => 'theme',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'choices' => array(
						'dark' => 'Dark Theme (light links on a dark background)',
						'light' => 'Light Theme (dark links on a light background)',
					),
					'default_value' => false,
					'allow_null' => 1,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'placeholder' => '',
					'ajax' => 0,
				),
				array(
					'key' => 'field_5f97591068310',
					'label' => 'Background Color',
					'name' => 'background_color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'transparent' => 'Transparent',
						'primary' => 'Theme Primary Color',
						'secondary' => 'Theme Secondary Color',
						'tertiary' => 'Theme Tertiary Color',
						'custom' => 'Custom Color',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 1,
					'ajax' => 0,
					'return_format' => 'value',
					'allow_custom' => 0,
					'search_placeholder' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f97597668311',
					'label' => 'Custom Background Color',
					'name' => 'custom_background_color',
					'type' => 'color_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f97591068310',
								'operator' => '==',
								'value' => 'custom',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
				),
				array(
					'key' => 'field_5f975ac568316',
					'label' => 'Child Menu Type',
					'name' => 'child_type',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'none' => 'Flat style (no submenus)',
						'collapse' => 'Accordion Style',
						'dropdown' => 'Dropdown Style',
						'tab' => 'Tab Style',
					),
					'default_value' => false,
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'return_format' => 'value',
					'ajax' => 0,
					'placeholder' => '',
				),
				array(
					'key' => 'field_5f9759a468312',
					'label' => 'Navbar Options',
					'name' => 'navbar_options',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5f97580f6830d',
								'operator' => '==',
								'value' => 'navbar',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'layout' => 'block',
					'acfe_seamless_style' => 0,
					'acfe_group_modal' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_5f9759d068313',
							'label' => 'Items to add to the navbar',
							'name' => 'order',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'brand' => 'Logo',
								'text' => 'Custom Text',
								'search' => 'Search Bar',
								'toggle' => 'Responsive Toggle',
								'navbar' => 'The menu',
							),
							'default_value' => array(
								0 => 'brand',
								1 => 'navbar',
								2 => 'toggle',
							),
							'allow_null' => 1,
							'multiple' => 1,
							'ui' => 1,
							'ajax' => 0,
							'return_format' => 'value',
							'allow_custom' => 0,
							'placeholder' => '',
							'search_placeholder' => '',
						),
						array(
							'key' => 'field_5f975a2168314',
							'label' => 'Mobile Breakpoint',
							'name' => 'breakpoint',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_permissions' => '',
							'choices' => array(
								'xl' => 'Screens less than 1440px',
								'lg' => 'Screens less than 1280px',
								'ml' => 'Screens less than 1024px',
								'md' => 'Screens less than 768px',
								'ms' => 'Screens less than 576px',
								'sm' => 'Screens less than 375px',
							),
							'default_value' => 'ml',
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5f975b3668317',
							'label' => 'Custom Text',
							'name' => 'text',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f9759d068313',
										'operator' => '==contains',
										'value' => 'text',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'seemless-group',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5fa5b5713cdef',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
						array(
							'key' => 'field_602d90e8f3a05',
							'label' => 'Toggle Atts',
							'name' => 'toggle',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5f9759d068313',
										'operator' => '==contains',
										'value' => 'toggle',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => 'seamless-group',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5e6ff014bda80',
							),
							'display' => 'group',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
							'acfe_seamless_style' => 1,
							'acfe_clone_modal' => 0,
						),
					),
				),
				array(
					'key' => 'field_5f9b133481faa',
					'label' => 'Container Classes',
					'name' => 'container_class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5f9b133d81fab',
					'label' => 'Menu Classes',
					'name' => 'menu_class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_permissions' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'nav_menu',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
	'acfe_categories' => array(
		'theme' => 'Theme',
	),
	'modified' => 1613599976,
));

endif;